mytestkey=This value is from LOCAL properties file

# Sensitive data should never be in properties file, since it's just development and testing env it is fine
# AWS Secret Manager - keeping sensitive data

paypal.client.id=AbisXxOv9XcvjxT-6BAguN24o5QkBLLcvFV0YpIYlWUJCZgUfWxJsREdVN_kxSEmCuOAA-BVoMcHkPxz
paypal.client.secret=EJEiW9g-vuQ28yr1KBDa6_1cP48zvSIe_KCPSiUJNnxTcXTr8pJmtpJxpvRxya9z6UxvODevw2GbjGva
paypal.outh.url=https://api-m.sandbox.paypal.com/v1/oauth2/token
