# Server Configuration
server.address=0.0.0.0

# Sensitive data should be stored in AWS Secrets Manager and not in properties files

# PayPal Sandbox Credentials
# paypal.client.id=<Reading from AWS Secrets Manager>
# paypal.client.secret=<Reading from AWS Secrets Manager>

# AWS Secrets Manager PayPal Sandbox Credentials
spring.config.import=aws-secretsmanager:dev/paypal-provider-service

# PayPal API Endpoints
paypal.outh.url=https://api-m.sandbox.paypal.com/v1/oauth2/token
paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.show.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture

# root level Configuration
logging.level.com.hulkhiretech.payments=DEBUG

# Redis Configuration
spring.redis.host= # EC2 endpoint to be added
spring.redis.port=6379
spring.redis.password= # Leave empty